files:
  - source: /**/values/evolution_strings.xml
    translation: /%original_path%-%android_code%/%original_file_name%
  - source: /**/values/evolution_arrays.xml
    translation: /%original_path%-%android_code%/%original_file_name%
