/*
* Copyright (C) 2017 The Pixel Experience Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package com.android.internal.util.evolution;

public class OverlayUtils {
    public static String[] AllPackages = {
            "com.android.documentsui.theme.dark",
            "com.android.systemui.custom.theme.dark",
            "com.android.gboard.theme.dark",
            "com.android.settings.intelligence.theme.dark",
            "com.android.wellbeing.theme",
            "com.android.system.theme.dark",
            "com.android.settings.theme.dark",
            "org.evolutionx.ota.theme.dark",
            "com.android.documentsui.theme.black",
            "com.android.systemui.custom.theme.black",
            "com.android.system.theme.black",
            "org.evolutionx.ota.theme.black",
            "org.pixelexperience.overlay.accent.cyan",
            "org.pixelexperience.overlay.accent.purple",
            "org.pixelexperience.overlay.accent.white",
            "org.pixelexperience.overlay.accent.red",
            "org.pixelexperience.overlay.accent.brown",
            "org.pixelexperience.overlay.accent.yellow",
            "org.pixelexperience.overlay.accent.teal",
            "org.pixelexperience.overlay.accent.black",
            "org.pixelexperience.overlay.accent.orange",
            "org.pixelexperience.overlay.accent.green",
            "org.pixelexperience.overlay.accent.pink",
            "org.evolutionx.overlay.accent.pixelblue",
            "org.evolutionx.overlay.accent.qcinnamon",
            "org.evolutionx.overlay.accent.qocean",
            "org.evolutionx.overlay.accent.qorchid",
            "org.evolutionx.overlay.accent.qspace",
            "org.evolutionx.overlay.accent.aospa",
            "org.evolutionx.overlay.accent.androidone",
            "org.evolutionx.overlay.accent.cocacola",
            "org.evolutionx.overlay.accent.discord",
            "org.evolutionx.overlay.accent.facebook",
            "org.evolutionx.overlay.accent.instagram",
            "org.evolutionx.overlay.accent.jollibee",
            "org.evolutionx.overlay.accent.monster",
            "org.evolutionx.overlay.accent.nextbit",
            "org.evolutionx.overlay.accent.oneplus",
            "org.evolutionx.overlay.accent.pepsi",
            "org.evolutionx.overlay.accent.poco",
            "org.evolutionx.overlay.accent.razer",
            "org.evolutionx.overlay.accent.samsung",
            "org.evolutionx.overlay.accent.spotify",
            "org.evolutionx.overlay.accent.starbucks",
            "org.evolutionx.overlay.accent.twitch",
            "org.evolutionx.overlay.accent.twitter",
            "org.evolutionx.overlay.accent.xbox",
            "org.evolutionx.overlay.accent.xiaomi",
            "com.google.android.theme.almostproblue",
            "com.google.android.theme.bubblegumpink",
            "com.google.android.theme.burningred",
            "com.google.android.theme.coldbleu",
            "com.google.android.theme.dawnred",
            "com.google.android.theme.diffdaygreen",
            "com.google.android.theme.dimigouig",
            "com.google.android.theme.dreamypurple",
            "com.google.android.theme.drownedaqua",
            "com.google.android.theme.duskpurple",
            "com.google.android.theme.frenchbleu",
            "com.google.android.theme.grapespurple",
            "com.google.android.theme.heirloombleu",
            "com.google.android.theme.holillusion",
            "com.google.android.theme.labouchered",
            "com.google.android.theme.limedgreen",
            "com.google.android.theme.lunablue",
            "com.google.android.theme.maniamber",
            "com.google.android.theme.misleadingred",
            "com.google.android.theme.movemint",
            "com.google.android.theme.naturedgreen",
            "com.google.android.theme.newhouseorange",
            "com.google.android.theme.notimppurple",
            "com.google.android.theme.obfusbleu",
            "com.google.android.theme.spoofygreen",
            "com.google.android.theme.spookedpurple",
            "com.google.android.theme.sunsetorange",
            "com.google.android.theme.warmthorange",
            "com.google.android.theme.whythisgrey",
            "com.potato.overlay.accent.armygreen",
            "com.potato.overlay.accent.deepred",
            "com.potato.overlay.accent.fadedpink",
            "com.potato.overlay.accent.grey",
            "com.potato.overlay.accent.kindaindigo",
            "com.potato.overlay.accent.pinkred",
            "com.android.gboard.theme.light",
            "org.pixelexperience.overlay.hidecutout",
            "com.android.facelock.theme.dark",
            "com.google.android.setupwizard.overlay",
            "com.android.systemui.qstile.default",
            "com.android.systemui.qstile.circletrim",
            "com.android.systemui.qstile.dualtonecircletrim",
            "com.android.systemui.qstile.squircletrim",
            "com.android.systemui.qstile.circlegradient",
            "com.android.systemui.qstile.wavey",
            "com.android.systemui.qstile.circledualtone",
            "com.android.systemui.qstile.pokesign",
            "com.android.systemui.qstile.ninja",
            "com.android.systemui.qstile.dottedcircle",
            "com.android.systemui.qstile.attemptmountain",
            "com.android.systemui.qstile.squaremedo",
            "com.android.systemui.qstile.hexagon",
            "com.android.systemui.qstile.star",
            "com.android.systemui.qstile.gear",
            "com.android.systemui.qstile.diamond",
            "com.android.systemui.qstile.cookie",
            "com.android.systemui.qstile.circleoutline",
            "com.android.systemui.qstile.roundedrect",
            "com.android.systemui.qstile.square",
            "com.android.systemui.qstile.squircle",
            "com.android.systemui.qstile.teardrop",
            "com.android.systemui.qstile.badge",
            "com.android.systemui.qstile.badgetwo",
            "com.android.systemui.qstile.triangle",
            "com.android.systemui.qstile.oos",
    };
}
